# -*- coding: utf-8 -*-
"""BERT_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcvPlziMBRk_chCmq1KKwhGJUNLNF-Oe
"""

import os
os.environ["WANDB_DISABLED"] = "true"

!pip install -U transformers

# ✅ Fine-tune BERT on 'product_reviews.csv' (3-class sentiment classification)
# 🔧 Install required packages
!pip install transformers datasets scikit-learn

# 📚 Imports
import pandas as pd
import torch
from datasets import Dataset
from transformers import BertTokenizerFast, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 📥 Load your CSV data
df = pd.read_csv('/content/product_reviews.csv')  # Adjust path if needed

# 🧹 Clean and encode labels
df = df[['review', 'label']].dropna()
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['label'])

# 🔀 Train-test split
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['review'].tolist(), df['label'].tolist(), test_size=0.2, random_state=42)

# 🔤 Load tokenizer
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

# ✂️ Tokenize
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
val_encodings = tokenizer(val_texts, truncation=True, padding=True, max_length=128)

# 🔄 Convert to torch dataset
class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = SentimentDataset(train_encodings, train_labels)
val_dataset = SentimentDataset(val_encodings, val_labels)

# 🧠 Load model
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)

# ⚙️ Training arguments (no evaluation/save strategy)
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=1,  # only 1 per loop
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir='./logs',
    logging_steps=10,
)

# 🧰 Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer
)

# 🔁 Manual training loop (evaluate + save per epoch)
epochs = 3  # Total epochs you want to run
for epoch in range(epochs):
    print(f"\n🔁 Starting epoch {epoch+1}/{epochs}")

    trainer.train(resume_from_checkpoint=None)

    metrics = trainer.evaluate()
    print(f"📊 Evaluation results:", metrics)

    save_path = f"./bert-finetuned-epoch{epoch+1}"
    trainer.save_model(save_path)
    print(f"✅ Model saved to: {save_path}")

# 🔍 Prediction function
def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
        predicted_class = torch.argmax(outputs.logits, dim=1).item()
    return label_encoder.inverse_transform([predicted_class])[0]

# 📝 User input
user_input = input("Enter a product review: ")
print("Predicted sentiment:", predict_sentiment(user_input))